### ISSUE TITLE
Illegal move a8a8 encountered

### ISSUE THREAD

**Issue by tonymokonen** [jhonnold/berserk#14]
I was using the non-popcount compile of Berzerk 2.0.0, and I ran into an illegal move.  It was a position where Berzerk had a king and bishop, and my program had a king and pawn. My program was getting ready to try and promote, and Berzerk was forced to capture the pawn in order to prevent the pawn promotion. In the PVs before the illegal move, Berzerk indicated that it saw the draw, but when it came time to actually make the pawn capture, it performed the illegal move.

I have uploaded an Arena log file here:

http://tonyschess.x10host.com/BerzerkLog.rar

Unfortunately, the first few moves of the game were truncated from the log, but I doubt they had any effect on the bug.

Tony

**Comment by jhonnold** [comment]
Thank you for reporting this! I've seen this myself while running engine tests. The log output you're supplying me should be very helpful in debugging.
