### ISSUE TITLE
Cannot compile Bersek 2.0.0 on Linux 64

### ISSUE THREAD

**Issue by rchastain** [jhonnold/berserk#16]
Hello! I try to compile the engine on Linux 64 and get this message:

```
[roland@localhost src]$ LC_ALL=C make
gcc -O3 -std=gnu11 -Wall -Wextra -Wshadow -flto -march=native *.c -o berserk
/usr/bin/ld: /tmp/ccdLrmTs.ltrans0.ltrans.o: in function `ttInit':
<artificial>:(.text+0x4eca): undefined reference to `log2'
collect2: error: ld returned 1 exit status
make: *** [makefile:9: all] Error 1
[roland@localhost src]$
``` 

Would you know how to solve this?

Regards.

Roland

**Comment by jhonnold** [comment]
I have a fix for this issue in the next release. It's due to a lack of linking the math library for LLVM compilers. This can be solved quickly by adding `-lm` to any of the FLAGS in the makefile.

**Comment by jhonnold** [comment]
If you compile at this commit: https://github.com/jhonnold/berserk/commit/60616c4a3dd18c41e852965e62c65ed637b8bcaa it will solve this issue.

**Comment by rchastain** [comment]
Indeed, problem solved. Thank you.
