### ISSUE TITLE
how to use branches / tags ?

### ISSUE THREAD

**Issue by tissatussa** [jhonnold/berserk#289]
i always wondered how to 'use' the different versions of GitHub projects (like yours) as shown when clicking the button "switch branches or tags" .. can you explain or give a link to some doc ?  [i can ask this question to any developer on GitHub, i know]

i find many interesting (chess) projects on GitHub and i try to use them by compiling their sources .. therefor i learned to do a 'git clone' by using the green 'Code' button and copy an URL like your https://github.com/jhonnold/berserk.git to use in terminal .. however, when clicking the button "switch branches or tags", which defaults to 'main' or sometimes 'master', i can see any file & folder list, eg. like this 'tag 5' version :

![berserk5](https://user-images.githubusercontent.com/1109281/141441961-fcfbe69c-100e-4521-b450-47ecbb32c014.png)

besides the question if it's useful anyway, how can i copy such source tree? In this mode, the green Code button is still visible, but it doesn't give me another .git URL .. also 'Download ZIP' still supplies code of the Main branch .. i read GitHub Docs 'About remote repositories' at https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories but it does not bring me answers ..

another thing in this regard : why do you keep all those branches and tags ?  Will anyone use these anytime ?  Then how and for what purpose ?

some developers at GitHub maintain their code in a different way -- i don't know if it's correct what they're doing : compiling their 'Main' code gives a development version (being their current latest code), which is visible in the version number after doing the 'uci' command (regarding code of an UCI chess engine). So their 'Main' version is not equal to their 'Latest' release, which confuses me ..

**Comment by amanjpro** [comment]
In the command line type:

`git checkout <BRANCH_OR_TAG_NAME>`

Replace `<BRANCH_OR_TAG_NAME>` with the branch or tag name that you want to checkout (use)

**Comment by jhonnold** [comment]
I do not believe this the appropriate place to have a discussion about the usage of `git`.

I recommend you read [a general guide](https://rogerdudler.github.io/git-guide/).
