### ISSUE TITLE
Nice engine ... it won a strange game but lost almost always at depth 8.

### ISSUE THREAD

**Issue by Zibri** [jhonnold/berserk#345]
First of all, congrats for this engine.
I really like it and perhaps there is space for optimization.

This is what just happened on my computer:
berserk won against stockfish in this game https://lichess.org/rImqMlia

**Comment by Zibri** [comment]
Also: while berserk works in pychess, it does not in CuteChess for some reason.

**Comment by jhonnold** [comment]
I'm not sure what the issue is. Stockfish is significantly stronger than Berserk.
