### ISSUE TITLE
Berserk, the beast we are looking for to develop Chess Variants

### ISSUE THREAD

**Issue by musketeerchess** [jhonnold/berserk#351]
Hi everyone,
Thank you for this nice engine.

I wonder if you can make an engine playing Chess Variants. The inspiration can come from Stockfish and the excellent Fabian Fichter who's work is simply outstanding.

This project could be also for a Ph D and i can help with that. Please send me a private message and check my website musketeerchess . net

**Comment by jhonnold** [comment]
Thanks for the compliment on Berserk. Currently my only interest in continuing chess development would be for standard and FRC.
