### ISSUE TITLE
Headerification proposal

### ISSUE THREAD

**Issue by FrozenVoid** [jhonnold/berserk#355]
All .c files could be converted to
 headers, like bits.c/bits.h, but instead 
of bits.c including bits.h, 
only berserk.c would include header.h.
This would reduce clutter of multiple
 redundant includes, allow whole 
program optimization(vs LTO) and make compilation much faster as compiler and linker will use a single symbol map.

**Comment by jhonnold** [comment]
Looking at PR #356, this doesn't seem to decrease clutter. With Berserk's compilation already being fast as is, I don't see any benefits to introducing this change.

**Comment by FrozenVoid** [comment]
This reduces berserk(excluding network size) executable by ~10%
, see pull request.

**Comment by jhonnold** [comment]
If executable size is a concern, I think there are other ways to go about addressing that (such as `strip` after the fact), but also not-embedding the network. This feels like a good intention proposal, but I think it is considered a bad practice.

**Comment by FrozenVoid** [comment]
Your dumb code spammed my email 100 times with "failed tests" due your workflow
script considering every commit as new program, you cannot read code and demand formatting for essentially
 a hobby project i am not paid for - formatting that i consider cosmetic and superfluous vanity for people who can't read C.

A person who 
thinks 10% of executable size is insignificant isn't qualified to
 write anything more complex than tic-tac-toe examples.
I have deleted this fork and will not consider this project in the future.
