### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by SzotsGabor** [jhonnold/berserk#386]
Jay, I have problem with compiling. I'm on Windows 10, using the makefile I get this message:

process_begin: CreateProcess(NULL, git submodule update --init, ...) failed.
make (e=2): A rendszer nem találja a megadott fájlt. (in English: File not found.)

mingw32-make: *** [makefile:89: clone-networks] Error 2

Any hints?

**Comment by SzotsGabor** [comment]
Thanks, it seems it was not in the path. Now success.

**Comment by jhonnold** [comment]
If everything is working, I'll resolve this issue. If you do run into any more issues, feel free to re-open or create a separate issue.
