### ISSUE TITLE
Berserk Eval File

### ISSUE THREAD

**Issue by gabrielp10031978** [jhonnold/berserk#389]
Hello Mr,
This is not an issue.
I don't know what type of eval file Berserk it is using.
From this site: https://tests.stockfishchess.org/nns  ?
Please help me.
Thanks a lot.

**Comment by jhonnold** [comment]
It uses networks from [this repository](https://github.com/jhonnold/berserk-networks). Berserk does not support SF NNs as the architectures are completely different.

*Please note that all releases have an embedded network, and you don't need to specify an EvalFile*
