### ISSUE TITLE
Berserk 9 all builds crash very often on Windows and Mac M1

### ISSUE THREAD

**Issue by microsmeta** [jhonnold/berserk#401]
Hi!
I like Berserk a lot. Maybe it is the best free open source original chess engine. But it crashes very often, at least using Banksiagui on Mac M1 (but even your Windows popcnt sse41 builds). Suddenly it hangs in timeout and loses by time. Tried also various move overhead values (default 300)  from 100 to 10000 and hash 64 up 256 Mb not only 20220725 build, even old ones crash. No issues with other engines like Koivisto 8.13 or Seer 2.5.0 on Banksiagui 0.54

It seems that is crashes always on same position (watch image), starting a game with a different opening sometimes solves the issue for a while.

![berserk](https://user-images.githubusercontent.com/8478683/183019745-c2fbde01-12e0-4f70-95ef-008c8d5c2c68.png)

Log ends with:
banksia > Timeleft for Berserk 9: 1784.80, used: 1789.85, ProteusSF 030822: 1748.69
no errors but if you want I'm available to give you more feedbacks to solve this issue with you. Just tell me what to try. It's really a pity because it's a very good engine (M1 build compiled by Darius) https://www.chessengeria.com/post/interview-with-jay-honnold

**Comment by jhonnold** [comment]
Please confirm that this is still an issue. I suspect this was an issue when I was working on a larger network in Berserk causing stack allocations to be too high on Macs.

**Comment by microsmeta** [comment]
Thank you dear,
 Compiled (from github was giving me an error due to -march=native not supported. I've removed it from makefile, added 
#include <stdlib.h> to nn.c and compiled in local. Now I test the build.

Keep in touch, I'm a Berserk fan :)

uci
id name Berserk 20220905
id author Jay Honnold
option name Hash type spin default 32 min 4 max 65536
option name Threads type spin default 1 min 1 max 256
option name SyzygyPath type string default <empty>
option name MultiPV type spin default 1 min 1 max 256
option name Ponder type check default false
option name UCI_Chess960 type check default false
option name MoveOverhead type spin default 300 min 100 max 10000
option name Contempt type spin default 12 min -100 max 100
option name EvalFile type string default <empty>
uciok

**Comment by microsmeta** [comment]
![all ok](https://user-images.githubusercontent.com/8478683/189409137-19e66527-609f-437b-8947-abe72c1aa314.png)
All OK until now!

**Comment by microsmeta** [comment]
After eleven 30 min + 15 secs  /  all games, not a single crash, thank you you have solved the issue!
And it is also very strong, probably the best original engine with Dragon 3 ~3600 ELO
![very-good](https://user-images.githubusercontent.com/8478683/189470630-02d57bd9-aba3-4fa5-9b4c-193965c6c28e.png)

**Comment by jhonnold** [comment]
Resolving as there is no longer an issue.
