### ISSUE TITLE
cannot run on chess-cli

### ISSUE THREAD

**Issue by Negatil07** [jhonnold/berserk#406]
../etc/c-chess-cli.conf: line 4: unexpected EOF while looking for matching `"'
../etc/c-chess-cli.conf: line 10: syntax error: unexpected end of file

**Comment by jhonnold** [comment]
Can you go into more detail why this is a Berserk issue?

**Comment by Negatil07** [comment]
> Can you go into more detail why this is a Berserk issue?

Because, some other chess engine i will tested on chess-cli is ok fine.

**Comment by jhonnold** [comment]
From what I can see in the error message above, this is an issue with the configuration file for c-chess-cli and not the engine itself. Please confirm that you did not make an error when writing the configuration for Berserk.

**Comment by jhonnold** [comment]
Closing as this is clearly a missing `"` in the configuration file (from the error message).
