### ISSUE TITLE
Build error 1

### ISSUE THREAD

**Issue by mkrcmarik** [jhonnold/berserk#415]
Hi,
I'm trying to compile berserk using cygwin without success.
The following message is displayed when make basic is executed:

$ make basic
git submodule update --init
gcc -std=gnu11 -Wall -Wextra -Wshadow -Werror -O3 -flto -g -DVERSION=\"10\" -DEVALFILE=\"networks/berserk-c982d9682d4e.nn\" -DNDEBUG -march=native *.c pyrrhic/tbprobe.c -pthread -lm -o berserk
/tmp/ccBY6UyE.s: Assembler messages:
/tmp/ccBY6UyE.s:8: Warning: .type pseudo-op used outside of .def/.endef: ignored.
/tmp/ccBY6UyE.s:8: Error: junk at end of line, first unrecognized character is `K'
/tmp/ccBY6UyE.s:13: Warning: .type pseudo-op used outside of .def/.endef: ignored.
/tmp/ccBY6UyE.s:13: Error: junk at end of line, first unrecognized character is `K'
/tmp/ccBY6UyE.s:18: Warning: .type pseudo-op used outside of .def/.endef: ignored.
/tmp/ccBY6UyE.s:18: Error: junk at end of line, first unrecognized character is `K'
/tmp/ccBY6UyE.s:27: Warning: .type pseudo-op used outside of .def/.endef: ignored.
/tmp/ccBY6UyE.s:27: Error: junk at end of line, first unrecognized character is `K'
/tmp/ccBY6UyE.s:32: Warning: .type pseudo-op used outside of .def/.endef: ignored.
/tmp/ccBY6UyE.s:32: Error: junk at end of line, first unrecognized character is `K'
/tmp/ccBY6UyE.s:37: Warning: .type pseudo-op used outside of .def/.endef: ignored.
/tmp/ccBY6UyE.s:37: Error: junk at end of line, first unrecognized character is `K'
/tmp/ccBY6UyE.s:46: Warning: .type pseudo-op used outside of .def/.endef: ignored.
/tmp/ccBY6UyE.s:46: Error: junk at end of line, first unrecognized character is `E'
/tmp/ccBY6UyE.s:51: Warning: .type pseudo-op used outside of .def/.endef: ignored.
/tmp/ccBY6UyE.s:51: Error: junk at end of line, first unrecognized character is `E'
/tmp/ccBY6UyE.s:56: Warning: .type pseudo-op used outside of .def/.endef: ignored.
/tmp/ccBY6UyE.s:56: Error: junk at end of line, first unrecognized character is `E'
lto-wrapper: fatal error: gcc returned 1 exit status
compilation terminated.
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make: *** [makefile:58: basic] Error 1

**Comment by jhonnold** [comment]
Not a compiler I care to support.
