### ISSUE TITLE
Building berserk on MacOS Ventura

### ISSUE THREAD

**Issue by tkmilbaugh** [jhonnold/berserk#478]
Is it possible to build berserk on the latest MacOS?

**Comment by jhonnold** [comment]
Is this question relating to the OS or to Macs ARM processors?

**Comment by tkmilbaugh** [comment]
I really pertains to both the OS and the processor. I would like to build and run it on my Mac Studio with M1 Max.

**Comment by jhonnold** [comment]
It builds on Ventura without issue (at least for my intel MacBook Pro). I have no M1 and have not been able to test it's ability on that processor. I doubt it will to be honest.

**Comment by jhonnold** [comment]
Berserk will not compile on ARM machines.
