### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by ellxor** [jhonnold/berserk#498]
Berserk segfaults when analysing a position with more than 128 moves, such as:
FEN: 3Q4/1Q4Q1/4Q3/2Q4R/Q4Q2/3Q4/1Q4Rp/1K1BBNNk w - -

This position has 218 legal moves which is considered to be the most of any legal position (that anyone has constructed so far...)

I believe a simple fix is to redefine `MAX_MOVES` from 128 to 218 in `types.h`- at least that worked for me after a brief check. Obviously this will likely make a small reduction in engine performance for the sake of full legal completeness. Maybe this is something you have already considered, but I did find a position in lichess elite database from a real game with more than 128 legal moves.

**Comment by jhonnold** [comment]
> but I did find a position in lichess elite database from a real game with more than 128 legal moves.

What is that position?

**Comment by ellxor** [comment]
I don't have an exact FEN or link to the game, but one player had promoted to 8 queens in an endgame.

**Comment by jhonnold** [comment]
Alright, I'm not too concerned about that happening in an Engine v Engine match up where engines play for mate rather than bad manners :)
