### ISSUE TITLE
Problem in Arena with "Time per move"

### ISSUE THREAD

**Issue by KohKahHuat** [jhonnold/berserk#500]
I am using Arena 3.5.1 on Windows 10 Home, 8Gb memory, Berserk 20230818 compiled by Ipman.  The only Berserk's parameter that I changed is from default contempt to contempt 16. Time per move in Arena is set to 12 mins per move for the following position:

r2qk2r/1ppnbpp1/4pn1p/pP3b2/2p5/P4NP1/1B1PPPBP/RN1Q1RK1 w kq - 0 10 

Berserk 20230818 made a move in less than 300 secs whereas Stockfish 20230706, Komodo 14.1, Chess-System-Tal 2.0 made the move only used up the full 12 mins.

Is there a bug in Berserk 20230818 for "Time per move"? Thank you.

Best wishes,
Koh, Kah Huat

**Comment by jhonnold** [comment]
Berserk is not following `movetime`. I'll get a fix out for this.

**Comment by KohKahHuat** [comment]
Dear Sir,

Thank you for your prompt response and active action.
I'm quite a dummy user of chess engine and await, hopefully not too long, some kind guys will compile (bmi or avx2) and release your fixed version.

Once again, thank you for help and a free + great chess engine.

Best wishes,
Koh, Kah Huat

________________________________
