### ISSUE TITLE
Error - Berserk 12

### ISSUE THREAD

**Issue by Krzychumag** [jhonnold/berserk#527]
Warmly welcome jhonnold,
I have a request for you. Can you see this link https://talkchess.com/forum3/viewtopic.php?f=2&t=82864 and answer the question what was the reason for the error in this link? Thank you in advance for your answer. 

Regards
Krzysztof

**Comment by Krzychumag** [comment]
What information are you requesting.

**Comment by jhonnold** [comment]
- Berserk version
- PGN logs
- Engine parameters (TC, Threads, Hash)

Most likely this is just an issue that won't be resolvable. If I reproduce it on my system, then it's something I can look at in the future.

**Comment by Krzychumag** [comment]
Berserk version  - 12
Engines parameters - TC= 3 minutes + 2 seconds, Threads= 32  Hash=16384
PGN logs - Unfortunately, I don't have this

**Comment by jhonnold** [comment]
Without logs and others reporting crashes I'm going to resolve this issue. If you experience another crash or I receive reports from others, I will reopen this and continue investigation.

_I have run probably a million games since this was reported and have not seen a crash._
