### ISSUE TITLE
OpenBench access

### ISSUE THREAD

**Issue by ArjunBasandrai** [jhonnold/berserk#531]
Hi Jay,
Arjun this side

I am working on the Shuffle Chess Engine right now. I was wondering how can I get access to the OpenBench framework. Is there a specific procedure I need to follow? 

I mailed Andrew Grant on the email address mentioned on his Github Profile, but I havent heard back from him. 

Can you please guide me on this issue?

**Comment by jhonnold** [comment]
I recommend you reach out to him via discord. You can find a link to that via the main OB instance - http://chess.grantnet.us.

**Comment by ArjunBasandrai** [comment]
Okay!
Thank you so much responding.

Have a great day!
