### ISSUE TITLE
Can I train a separate eval network？

### ISSUE THREAD

**Issue by nimeng1299** [jhonnold/berserk#557]
Can I train a separate eval network myself? If possible, how should I train?

**Comment by jhonnold** [comment]
You're welcome to do as you please as long as you follow GPL licensing if publishing a release.

I use the [Grapheus Trainer](https://github.com/Luecx/Grapheus/blob/main/src/models/berserk.h) which has my model built in. My data is kept locally and I simply don't have the means to upload it, you'd have to find/generate your own dataset.

**Comment by nimeng1299** [comment]
> You're welcome to do as you please as long as you follow GPL licensing if publishing a release.
> 
> I use the [Grapheus Trainer](https://github.com/Luecx/Grapheus/blob/main/src/models/berserk.h) which has my model built in. My data is kept locally and I simply don't have the means to upload it, you'd have to find/generate your own dataset.

Thank you for your reply. How do I generate a dataset? Is there a training dataset generator like Stockfish?

**Comment by nimeng1299** [comment]
i use [nnue-fen-gen-alt](https://github.com/jhonnold/berserk/tree/nnue-fen-gen-alt) to run some .fens, but it doesn't seem to be suitable for Grapheus Trainer. How should I convert this fens?

**Comment by jhonnold** [comment]
https://github.com/Luecx/fin-tool
