### ISSUE TITLE
display of the selective depth when using "go movetime" and more

### ISSUE THREAD

**Issue by BrennusJ** [jhonnold/berserk#559]
Hello,

Sometime, when i'musing "go movetime" the selective depth displayed is inferior to the global depth : how it is possible ?
Is the selective depth diplayed is the greater selective depth of any branch ?

Something else : the UCI command "uci_opponent" will be welcome
It is very usefull to adapt Contempt regarding the ELO of the opponent
For exemple using Berserk in Lichess-bot python script you can setting the engine in different way if you detect à BOT or an HUMAN

Regards

**Comment by jhonnold** [comment]
Depth is just a general value to indicate to the user how many iterations of internal deepening have occurred and tends to align with the length of the principal variation. Selective depth is the highest depth reached on any branch within the search tree.

Selective depth has no requirement to be a higher value than depth. For example in a mate in 1 position, I would expect depth to be 200 and selective depth to be 1. 200 iterations of internal deepening happened, but Berserk had no reason to go farther than depth 1 in any branch. In positions where a draw is best, I would expect a similar output.
