### ISSUE TITLE
Sorting wining ply and 'drawn by threefold repetition' detection

### ISSUE THREAD

**Issue by BrennusJ** [jhonnold/berserk#560]
In this position :

8/6PK/3k4/8/8/8/8/8 w - - 9 93

Berserk find M10 for Kg6  and g8=Q but Kg6 is on top

Any human player will play g8=Q

In my oppinion by analysing this game in Lichess : [https://lichess.org/R0rcek4r](url)
Where ELO_1500 is Berserk (running at home on RPB4) this problem could also be linked with a problem in  drawn by threefold repetition detection (tablebase are activated)
i join the log generated by lichess-bot script
[lichess_pgn_2024.05.21_ELO_1500_vs_AKS-Mantissa.R0rcek4r.pgn.log](https://github.com/jhonnold/berserk/files/15388728/lichess_pgn_2024.05.21_ELO_1500_vs_AKS-Mantissa.R0rcek4r.pgn.log)
[strange-lost-berserk.log](https://github.com/jhonnold/berserk/files/15388669/strange-lost-berserk.log)

wining ply given by tablebase should be also verify to avoid "drawn by threefold repetition"

**Comment by jhonnold** [comment]
Berserk found an optimal path to mate, I see no issue here. Expecting Berserk to act like a human is nonsense as then it should blunder more frequently.
