### ISSUE TITLE
No Bmi2 version?

### ISSUE THREAD

**Issue by CurvedSilver** [jhonnold/berserk#563]
hi, tried all yr variants of engines , unfortunately, only using 1 of my 2 cpus  (50% of available only being used) , Are you able to make a bmi2 version?
Kind regards...

**Comment by jhonnold** [comment]
`pext` is a `bmi2` operation, that is the version that you're asking for. That being said, bmi2 has nothing to do with using all CPUs, that's the Thread count, which can be modified by setting the uci parameter.

```
setoption name Threads value 2
```
