### ISSUE TITLE
Crash when using perft  

### ISSUE THREAD

**Issue by Aryan1508** [jhonnold/berserk#87]
Noticed that the engine crashes when passed `go perft x` with a low depth. 

[perft.c  Line 77](https://github.com/jhonnold/berserk/blob/main/src/perft.c#L77)

```
printf("NPS: %ld\n\n", total / (endTime - startTime) * 1000);
```
Sometimes when the time taken is 0, it becomes `total / 0` which causes the crash.

**Comment by jhonnold** [comment]
Did you still plan to open a PR to resolve this @Aryan1508, or would you rather I just fix this issue?

**Comment by Aryan1508** [comment]
@jhonnold You can fix this
